CREATE TABLE IF NOT EXISTS records (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	date TEXT NOT NULL,
	description TEXT NOT NULL,
	category TEXT NOT NULL,
	amount REAL NOT NULL,
	type TEXT NOT NULL,
	notes TEXT
);
